/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-container": "#feb31b",
        "on-secondary-fixed": "#281800",
        "on-primary-fixed": "#001b3e",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1d3e6e",
        "surface-bright": "#f8f9fa",
        "primary": "#002855",
        "secondary": "#7f5600",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#aac7ff",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-highest": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "tertiary-fixed-dim": "#c6c6c6",
        "tertiary": "#272829",
        "on-secondary-fixed-variant": "#604100",
        "outline": "#747780",
        "surface-tint": "#405f91",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c6d0",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "inverse-primary": "#aac7ff",
        "secondary-fixed": "#ffdeae",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-container": "#8caae1",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#3d3e3f",
        "surface": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#a8a9a9",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#ffba3f",
        "background": "#f8f9fa",
        "on-error": "#ffffff",
        "on-surface-variant": "#43474f",
        "on-tertiary-fixed-variant": "#454747",
        "on-secondary-container": "#6b4800",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed-variant": "#274777",
        "error": "#ba1a1a",
        "surface-variant": "#e1e3e4",
        "inverse-surface": "#2e3132"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
